services:
  - type: web
    name: cat-cleaning-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        value: mongodb://localhost:27017/cat-cleaning
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true 